#!/bin/bash
# generate-secrets.sh
# Generate random secrets for homelab .env file

set -euo pipefail

# Function to generate a random string
generate_secret() {
  local length=${1:-32}
  # Use /dev/urandom for cryptographically random, base64 encode, cut to length
  head /dev/urandom | tr -dc 'A-Za-z0-9!@#$%^&*()_+=' | head -c ${length} || echo "RANDOM_SEED_${length}"
}

# Read .env.example to see what variables are needed, or define a list
# We'll define a list of known variables from the homelab setup
declare -A secrets=(
  ["POSTGRES_USER"]="homelab"
  ["POSTGRES_PASSWORD"]="$(generate_secret 24)"
  ["REDIS_PASSWORD"]="$(generate_secret 24)"
  ["AUTHENTIK_SECRET_KEY"]="$(generate_secret 32)"
  ["AUTHENTIK_BOOTSTRAP_EMAIL"]="admin@${DOMAIN:-homelab.local}"
  ["AUTHENTIK_BOOTSTRAP_PASSWORD"]="$(generate_secret 24)"
  ["AUTHENTIK_ADMIN_EMAIL"]="admin@${DOMAIN:-homelab.local}"
  ["VAULTWARDEN_ADMIN_TOKEN"]="$(generate_secret 32)"
  ["VAULTWARDEN_ADMIN_EMAIL"]="admin@${DOMAIN:-homelab.local}"
  ["VAULTWARDEN_ADMIN_PASSWORD"]="$(generate_secret 24)"
  ["NUT_PASSWORD"]="$(generate_secret 24)"
  ["BESZEL_KEY"]="$(generate_secret 32)"
  ["BESZEL_TOKEN"]="$(generate_secret 32)"
  ["GF_SECURITY_ADMIN_PASSWORD"]="$(generate_secret 24)"
  ["N8N_BASIC_AUTH_USER"]="admin"
  ["N8N_BASIC_AUTH_PASSWORD"]="$(generate_secret 24)"
  ["STIRLING_PDF_INITIAL_PASSWORD"]="$(generate_secret 24)"
  ["S3_ACCESS_KEY"]="$(generate_secret 20)"   # For offsite backup if used
  ["S3_SECRET_KEY"]="$(generate_secret 40)"   # For offsite backup if used
  # SSO/OAuth client secrets
  ["GF_AUTH_GENERIC_OAUTH_CLIENT_ID"]="$(generate_secret 32)"
  ["GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET"]="$(generate_secret 32)"
  ["N8N_AUTH_OAUTH2_GENERIC_CLIENT_ID"]="$(generate_secret 32)"
  ["N8N_AUTH_OAUTH2_GENERIC_CLIENT_SECRET"]="$(generate_secret 32)"
  ["HOMEPAGE_AUTH_CLIENT_ID"]="$(generate_secret 32)"
  ["HOMEPAGE_AUTH_CLIENT_SECRET"]="$(generate_secret 32)"
  ["VAULTWARDEN_OIDC_CLIENT_ID"]="$(generate_secret 32)"
  ["VAULTWARDEN_OIDC_CLIENT_SECRET"]="$(generate_secret 32)"
  ["PORTAINER_OIDC_CLIENT_ID"]="$(generate_secret 32)"
  ["PORTAINER_OIDC_CLIENT_SECRET"]="$(generate_secret 32)"
  ["HOME_ASSISTANT_OAUTH2_CLIENT_ID"]="$(generate_secret 32)"
  ["HOME_ASSISTANT_OAUTH2_CLIENT_SECRET"]="$(generate_secret 32)"
  ["N8N_AUTH_OAUTH2_GENERIC_CLIENT_ID"]="$(generate_secret 32)"
  ["N8N_AUTH_OAUTH2_GENERIC_CLIENT_SECRET"]="$(generate_secret 32)"
)

# If .env exists, we want to preserve existing values and only fill missing ones
if [[ -f "../.env" ]]; then
  echo "Found existing .env, will only fill missing secrets."
  source ../.env 2>/dev/null || true
fi

# Generate the .env content
cat > ../.env.tmp <<EOF
# Homelab Environment Variables
# Auto-generated by generate-secrets.sh - edit as needed
# Required variables:
TZ=${TZ:-America/New_York}
DATA_PATH=${DATA_PATH:-/mnt/nvme/homelab2}
DOMAIN=${DOMAIN:-homelab.local}
# Secrets
POSTGRES_USER=${POSTGRES_USER:-${secrets[POSTGRES_USER]}}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-${secrets[POSTGRES_PASSWORD]}}
REDIS_PASSWORD=${REDIS_PASSWORD:-${secrets[REDIS_PASSWORD]}}
AUTHENTIK_SECRET_KEY=${AUTHENTIK_SECRET_KEY:-${secrets[AUTHENTIK_SECRET_KEY]}}
AUTHENTIK_BOOTSTRAP_EMAIL=${AUTHENTIK_BOOTSTRAP_EMAIL:-${secrets[AUTHENTIK_BOOTSTRAP_EMAIL]}}
AUTHENTIK_BOOTSTRAP_PASSWORD=${AUTHENTIK_BOOTSTRAP_PASSWORD:-${secrets[AUTHENTIK_BOOTSTRAP_PASSWORD]}}
AUTHENTIK_ADMIN_EMAIL=${AUTHENTIK_ADMIN_EMAIL:-${secrets[AUTHENTIK_ADMIN_EMAIL]}}
VAULTWARDEN_ADMIN_TOKEN=${VAULTWARDEN_ADMIN_TOKEN:-${secrets[VAULTWARDEN_ADMIN_TOKEN]}}
VAULTWARDEN_ADMIN_EMAIL=${VAULTWARDEN_ADMIN_EMAIL:-${secrets[VAULTWARDEN_ADMIN_EMAIL]}}
VAULTWARDEN_ADMIN_PASSWORD=${VAULTWARDEN_ADMIN_PASSWORD:-${secrets[VAULTWARDEN_ADMIN_PASSWORD]}}
NUT_PASSWORD=${NUT_PASSWORD:-${secrets[NUT_PASSWORD]}}
BESZEL_KEY=${BESZEL_KEY:-${secrets[BESZEL_KEY]}}
BESZEL_TOKEN=${BESZEL_TOKEN:-${secrets[BESZEL_TOKEN]}}
GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD:-${secrets[GF_SECURITY_ADMIN_PASSWORD]}}
N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER:-${secrets[N8N_BASIC_AUTH_USER]}}
N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD:-${secrets[N8N_BASIC_AUTH_PASSWORD]}}
S3_ACCESS_KEY=${S3_ACCESS_KEY:-${secrets[S3_ACCESS_KEY]}}
S3_SECRET_KEY=${S3_SECRET_KEY:-${secrets[S3_SECRET_KEY]}}
# SSO/OAuth client secrets
GF_AUTH_GENERIC_OAUTH_CLIENT_ID=${GF_AUTH_GENERIC_OAUTH_CLIENT_ID:-${secrets[GF_AUTH_GENERIC_OAUTH_CLIENT_ID]}}
GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET=${GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET:-${secrets[GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET]}}
N8N_AUTH_OAUTH2_GENERIC_CLIENT_ID=${N8N_AUTH_OAUTH2_GENERIC_CLIENT_ID:-${secrets[N8N_AUTH_OAUTH2_GENERIC_CLIENT_ID]}}
N8N_AUTH_OAUTH2_GENERIC_CLIENT_SECRET=${N8N_AUTH_OAUTH2_GENERIC_CLIENT_SECRET:-${secrets[N8N_AUTH_OAUTH2_GENERIC_CLIENT_SECRET]}}
HOMEPAGE_AUTH_CLIENT_ID=${HOMEPAGE_AUTH_CLIENT_ID:-${secrets[HOMEPAGE_AUTH_CLIENT_ID]}}
HOMEPAGE_AUTH_CLIENT_SECRET=${HOMEPAGE_AUTH_CLIENT_SECRET:-${secrets[HOMEPAGE_AUTH_CLIENT_SECRET]}}
VAULTWARDEN_OIDC_CLIENT_ID=${VAULTWARDEN_OIDC_CLIENT_ID:-${secrets[VAULTWARDEN_OIDC_CLIENT_ID]}}
VAULTWARDEN_OIDC_CLIENT_SECRET=${VAULTWARDEN_OIDC_CLIENT_SECRET:-${secrets[VAULTWARDEN_OIDC_CLIENT_SECRET]}}
PORTAINER_OIDC_CLIENT_ID=${PORTAINER_OIDC_CLIENT_ID:-${secrets[PORTAINER_OIDC_CLIENT_ID]}}
PORTAINER_OIDC_CLIENT_SECRET=${PORTAINER_OIDC_CLIENT_SECRET:-${secrets[PORTAINER_OIDC_CLIENT_SECRET]}}
HOME_ASSISTANT_OAUTH2_CLIENT_ID=${HOME_ASSISTANT_OAUTH2_CLIENT_ID:-${secrets[HOME_ASSISTANT_OAUTH2_CLIENT_ID]}}
HOME_ASSISTANT_OAUTH2_CLIENT_SECRET=${HOME_ASSISTANT_OAUTH2_CLIENT_SECRET:-${secrets[HOME_ASSISTANT_OAUTH2_CLIENT_SECRET]}}
# Tools links and native app login settings
TOOLS_PUBLIC_SCHEME=${TOOLS_PUBLIC_SCHEME:-http}
ACTUAL_PUBLIC_SCHEME=${ACTUAL_PUBLIC_SCHEME:-https}
ACTUAL_LOGIN_METHOD=${ACTUAL_LOGIN_METHOD:-password}
ACTUAL_ALLOWED_LOGIN_METHODS=${ACTUAL_ALLOWED_LOGIN_METHODS:-password,openid}
ACTUAL_TRUSTED_PROXIES=${ACTUAL_TRUSTED_PROXIES:-10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,fc00::/7,::1/128}
ACTUAL_HTTPS_KEY=${ACTUAL_HTTPS_KEY:-/data/selfhost.key}
ACTUAL_HTTPS_CERT=${ACTUAL_HTTPS_CERT:-/data/selfhost.crt}
STIRLING_PDF_ENABLE_LOGIN=${STIRLING_PDF_ENABLE_LOGIN:-true}
STIRLING_PDF_LOGIN_METHOD=${STIRLING_PDF_LOGIN_METHOD:-normal}
STIRLING_PDF_INITIAL_USERNAME=${STIRLING_PDF_INITIAL_USERNAME:-admin}
STIRLING_PDF_INITIAL_PASSWORD=${STIRLING_PDF_INITIAL_PASSWORD:-${secrets[STIRLING_PDF_INITIAL_PASSWORD]}}
# Optional features (set to enable)
# WOL_API_KEY=changeme   # For remote WoL API
# SMTP_USER=             # For email alerts
# SMTP_PASS=             # For email alerts
# SMARTHOST=             # For email alerts
EOF

# Overwrite .env if it doesn't exist, or if we want to regenerate (with warning)
if [[ ! -f "../.env" ]]; then
  mv ../.env.tmp ../.env
  echo "Generated new .env file"
else
  # Merge: take existing .env and overlay generated secrets for missing keys
  # We'll source the existing .env, then write back with generated values for any missing
  # But simpler: replace the whole file with the template, but preserve any custom additions?
  # For safety, we'll append missing lines if they don't exist.
  echo "Updating existing .env with any missing secrets (preserving existing values)..."
  while IFS='=' read -r key _; do
    # Skip empty lines and comments
    [[ -z "$key" || "$key" =~ ^# ]] && continue
    if ! grep -q "^${key}=" ../.env 2>/dev/null; then
      echo "${key}=${secrets[$key]:-}" >> ../.env
    fi
  done < <(grep -v '^#' ../.env.tmp | grep -v '^$' | cut -d= -f1)
  rm ../.env.tmp
  echo "Updated .env with missing secrets"
fi

# Show the generated secrets (excluding passwords for safety)
echo "=== Generated Secrets Summary ==="
grep -E '_(PASSWORD|TOKEN|SECRET|CLIENT)_' ../.env | while IFS= read -r line; do
  key=$(echo "$line" | cut -d= -f1)
  echo "$key: [REDACTED]"
done
echo "=== End Summary ==="
echo "Review ../.env and adjust as needed."
